name: Changeset
description: Opens Release PR or Deploys to NPM

runs:
  using: "composite"
  steps:
    - name: 1Password Load Tokens
      id: op-tokens
      uses: 1password/load-secrets-action@v1
      with:
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        NPM_TOKEN: op://dev/StylebucketCore/NPM/npm-token

    - name: Release Pull Request or Publish to NPM
      uses: changesets/action@v1
      with:
        publish: pnpm run changeset:publish
        version: pnpm run changeset:version
        # Version Commmit Message
        commit: "[CI] Changeset: Update Package Versions"
        # PR Title
        title: "[CI] Changeset: Prep Package Versions for Release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # NPM_TOKEN: set in steps.op-tokens (export-env: true)
