name: On PR Main

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  checks:
    name: Code Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Prep Project
        uses: ./.github/composite-actions/prep-project

      - name: Code Checks
        uses: ./.github/composite-actions/code-checks
