name: On Push Main
on:
  push:
    branches:
      - main

# So no other instances of release workflow run at same time
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  primary:
    name: Primary Tasks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Prep Project
        uses: ./.github/composite-actions/prep-project

      - name: Code Checks
        uses: ./.github/composite-actions/code-checks

      - name: 1Password Load Tokens
        id: op-tokens
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          NPM_TOKEN: op://dev/StylebucketCore/NPM/npm-token

      - name: Release Pull Request or Publish to NPM
        uses: changesets/action@v1
        with:
          publish: pnpm run changeset:publish
          version: pnpm run changeset:version
          # Version Commmit Message
          commit: "[CI] Changeset: Update Package Versions"
          # PR Title
          title: "[CI] Changeset: Prep Package Versions for Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: set in steps.op-tokens (export-env: true)
