name: On Push Main
on:
  push:
    branches:
      - main

# So no other instances of release workflow run at same time
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  primary:
    name: Primary Tasks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Prep Project
        uses: ./.github/composite-actions/prep-project

      - name: Code Checks
        uses: ./.github/composite-actions/code-checks

      - name: Changeset
        uses: ./.github/composite-actions/changeset
